/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IIonHome: typeof import('~icons/ion/home.jsx').default
  const IIonPerson: typeof import('~icons/ion/person.jsx').default
}
